#!/usr/bin/env python3
"""RedFox localization: replace English UI string literals in Kotlin sources
with their Persian equivalents. Only exact whole-literal matches are replaced,
so protocol names, preference keys, URLs and JSON keys are never touched."""
import re, sys, io

# English -> Persian (exact full-string match on the quoted literal)
M = {
    # ---- main / connect screen ----
    "Not connected": "قطع است",
    "Connecting": "در حال اتصال",
    "Connecting…": "در حال اتصال…",
    "Connected": "متصل",
    "Connection degraded": "اتصال ناپایدار",
    "Verifying": "در حال بررسی",
    "Tap the dial to connect": "برای اتصال روی دایره بزنید",
    "Settings": "تنظیمات",
    "Logs": "گزارش‌ها",
    "Done": "انجام شد",
    "Save": "ذخیره",
    "Back": "بازگشت",
    "Clear": "پاک کردن",
    "Retry": "تلاش مجدد",
    "Error": "خطا",
    "Unknown": "نامشخص",
    "Auto": "خودکار",
    "Automatic": "خودکار",
    "Custom": "سفارشی",
    "All apps": "همه‌ی برنامه‌ها",
    "Apps": "برنامه‌ها",
    "Search apps…": "جستجوی برنامه‌ها…",
    "Scanning installed apps…": "در حال بررسی برنامه‌های نصب‌شده…",
    "Exclude selected apps": "خروج برنامه‌های انتخابی از تونل",
    "Split tunneling": "تونل تفکیکی",
    "Kill switch": "قطع‌کننده‌ی اضطراری",
    "Traffic monitor": "نمایشگر ترافیک",
    "Tunnel controls": "کنترل‌های تونل",
    "Connection mode": "حالت اتصال",
    "Performance": "کارایی",
    "Preferred country": "کشور دلخواه",
    "Outer transport": "مسیر بیرونی",
    "Check for updates": "بررسی به‌روزرسانی",
    "Source on GitHub": "سورس در گیت‌هاب",
    "SELECTED": "انتخاب‌شده",
    "MODE": "حالت",
    "RETRY": "تلاش مجدد",
    "ABOUT": "درباره",
    "PROGRESS": "پیشرفت",
    "SPEED": "سرعت",
    "LIVE SPEED": "سرعت لحظه‌ای",
    "THIS SESSION": "این نشست",
    "THIS MONTH": "این ماه",
    "SPLIT": "تفکیک",
    "TROUBLESHOOTING": "عیب‌یابی",
    "PROTECTION": "محافظت",
    "ROUTING & DATA": "مسیریابی و داده",
    "CONNECTION": "اتصال",
    "ANTI-DPI": "ضد فیلترینگ",
    "VPN CORE": "هسته‌ی VPN",
    "PSIPHON": "سایفون",
    "TOR": "تور",
    "XRAY": "ایکس‌ری",
    "SCAN MODE": "حالت اسکن",
    "DEPRECATION": "منسوخ‌شده",
    "Core": "هسته",
    "Preset": "پیش‌تنظیم",
    "Default verbosity": "میزان پیش‌فرض جزئیات",
    "Full per-packet detail": "جزئیات کامل هر بسته",
    "Warnings and errors": "هشدارها و خطاها",
    "Warn": "هشدار",
    "Log level": "سطح گزارش",
    "Logs": "گزارش‌ها",
    "Moderate hardware": "سخت‌افزار متوسط",
    "Memory metrics at ": "مصرف حافظه در ",
    "COPY": "کپی",
    # ---- settings: tunnel controls / anti-DPI ----
    "Obfuscation": "اختفای ترافیک",
    "Advanced obfuscation": "اختفای پیشرفته",
    "WireGuard retries": "تلاش مجدد وای‌گارد",
    "WireGuard verification": "راستی‌آزمایی وای‌گارد",
    "WireGuard tunnel": "تونل وای‌گارد",
    "Manual endpoint": "نقطه‌ی پایانی دستی",
    "Gateway cache": "حافظه‌ی گیت‌وی",
    "TLS fingerprint": "اثرانگشت TLS",
    "TLS fragmentation": "تکه‌تکه‌سازی TLS",
    "Strict": "سخت‌گیرانه",
    "Fast": "سریع",
    "On": "روشن",
    "Off": "خاموش",
    "Cache & refresh": "کش و تازه‌سازی",
    "Fresh scan next time": "اسکن تازه در اتصال بعدی",
    "Clear saved gateways": "پاک‌کردن گیت‌وی‌های ذخیره‌شده",
    "Try saved gateways first": "ابتدا گیت‌وی‌های ذخیره‌شده امتحان شوند",
    "Use verified gateways first, then discover more": "ابتدا گیت‌وی‌های تأییدشده، سپس کشف موارد بیشتر",
    "Strict CONNECT-IP verification before selection": "راستی‌آزمایی سخت‌گیرانه‌ی CONNECT-IP پیش از انتخاب",
    "IP:port, blank for automatic": "IP:port — برای خودکار خالی بگذارید",
    "Numeric IPv4 or bracketed IPv6 address with port. Bypasses discovery.": "آدرس IPv4 عددی یا IPv6 با براکت به‌همراه پورت. کشف خودکار را دور می‌زند.",
    "Use whole numbers": "فقط عدد صحیح وارد کنید",
    "Jc must be 0–10": "مقدار Jc باید بین ۰ تا ۱۰ باشد",
    "Jmax must be 0–1024": "مقدار Jmax باید بین ۰ تا ۱۰۲۴ باشد",
    "Set dial parameters for ": "تنظیم پارامترهای اتصال برای ",
    "Applied on your next connection": "در اتصال بعدی شما اعمال می‌شود",
    # ---- performance ----
    "Turbo": "توربو",
    "Balanced": "متعادل",
    "Thorough": "دقیق",
    "Aggressive": "تهاجمی",
    "Compatibility": "سازگاری",
    "Stealth": "پنهان‌کار",
    "Light": "سبک",
    "Medium": "متوسط",
    "High": "بالا",
    "Slower": "کندتر",
    "Chrome": "کروم",
    "Fastest scan; first verified route wins": "سریع‌ترین اسکن؛ اولین مسیر تأییدشده برنده می‌شود",
    "Default mix of speed and coverage": "ترکیب پیش‌فرض سرعت و پوشش",
    "Deep scan; selects best latency": "اسکن عمیق؛ بهترین تأخیر انتخاب می‌شود",
    # ---- protocol descriptions ----
    "HTTP/3 tunnel": "تونل HTTP/3",
    "Double-layer tunnel": "تونل دولایه",
    "Anti-censorship tunnel": "تونل ضد سانسور",
    "Onion routing; slowest but hardest to block": "مسیریابی پیازی؛ کندتر ولی سخت‌ترین برای مسدودسازی",
    # ---- connection status / logs ----
    "IP unavailable": "IP در دسترس نیست",
    "Latency …": "تأخیر …",
    "Latency n/a": "تأخیر ناموجود",
    "Waiting for tunnel traffic": "در انتظار ترافیک تونل",
    "Tunnel stopped unexpectedly": "تونل به‌طور غیرمنتظره متوقف شد",
    "Tunnel is up but no traffic is passing": "تونل برقرار است اما ترافیکی عبور نمی‌کند",
    "Tunnel internals": "درون تونل",
    "Tunnel and VPN events": "رویدادهای تونل و VPN",
    "VPN permission required": "مجوز VPN لازم است",
    "tap to retry": "برای تلاش مجدد بزنید",
    "tap to refresh": "برای تازه‌سازی بزنید",
    "try Auto": "حالت خودکار را امتحان کنید",
    "did real payload arrive?": "آیا داده‌ی واقعی رسید؟",
    "start failure": "شکست در شروع",
    "all protocols (direct)": "همه‌ی پروتکل‌ها (مستقیم)",
    "port forward failures for ": "شکست‌های فوروارد پورت برای ",
    "updated server ": "سرور به‌روزرسانی‌شده ",
    "not locked mid-session": "در میانه‌ی نشست قفل نمی‌شود",
    "applies, but locked": "اعمال می‌شود، اما قفل است",
    # ---- psiphon / tor / chain ----
    "Tor over WARP": "تور روی WARP",
    "Tunnel Psiphon inside a WARP transport": "عبور سایفون از داخل یک مسیر WARP",
    "Which WARP tunnel carries Psiphon in Psiphon over WARP": "کدام تونل WARP سایفون را در حالت سایفون‌روی‌وارپ حمل کند",
    "Which WARP tunnel carries Tor in Tor over WARP": "کدام تونل WARP تور را در حالت تور‌روی‌وارپ حمل کند",
    "Tor tries to exit here. If it cannot, another country is used.": "تور تلاش می‌کند از این کشور خارج شود؛ در صورت نبود، کشور دیگری استفاده می‌شود.",
    "Tor is selected": "تور انتخاب شده است",
    "Tor connection mode set to Auto": "حالت اتصال تور روی خودکار تنظیم شد",
    "Tor-over-WARP outer transport set to Auto": "مسیر بیرونی تور‌روی‌وارپ روی خودکار تنظیم شد",
    "Trying all countries…": "در حال امتحان همه‌ی کشورها…",
    "via WoW": "از طریق WoW",
    "Let other devices use this tunnel · Psiphon only": "اجازه‌ی استفاده‌ی دستگاه‌های دیگر از این تونل · فقط سایفون",
    "Shaping · Anti-DPI": "شکل‌دهی ترافیک · ضد DPI",
    # ---- notifications ----
    "Upload": "ارسال",
    "Download": "دریافت",
    "Disconnect": "قطع",
    # ---- xray / subscription (new UI) ----
    "Subscription link": "لینک اشتراک (ساب)",
    "Config link": "لینک کانفیگ",
    "Manage configs": "مدیریت کانفیگ‌ها",
    "Add config": "افزودن کانفیگ",
    "Update subscription": "به‌روزرسانی اشتراک",
    "Paste your subscription URL": "لینک اشتراک خود را جای‌گذاری کنید",
    "Paste a config link (vless://, vmess://, trojan://, ss://)": "لینک کانفیگ را جای‌گذاری کنید (vless://، vmess://، trojan://، ss://)",
    "No config yet": "هنوز کانفیگی وجود ندارد",
    "Active config": "کانفیگ فعال",
    "Configs": "کانفیگ‌ها",
}

# Status detail fragments (used in template strings) — replace only when standalone.
files = sys.argv[1:]
total = 0
for path in files:
    with io.open(path, encoding="utf-8") as f:
        src = f.read()
    orig = src
    for en, fa in M.items():
        # match "English..." as a full quoted literal (double quotes)
        src = src.replace('"%s"' % en, '"%s"' % fa)
        # single-quoted Kotlin string
        src = src.replace("'%s'" % en, "'%s'" % fa)
    if src != orig:
        n = sum(1 for _ in [1])
        total += 1
        with io.open(path, "w", encoding="utf-8") as f:
            f.write(src)
        print("updated", path)
print("files changed:", total)
